import os
from dotenv import load_dotenv
load_dotenv()

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
import chainlit as cl
import ollama

DB_FAISS_PATH = "vectorstore/db_faiss"

SYSTEM_PROMPT = (
    "You are a helpful assistant knowledgeable about Indian history and culture. "
    "Use the provided context to answer questions. If the answer is not in the context, say you don't know. "
    "Be concise and helpful. Use the conversation history to resolve pronouns and follow-up references."
)

def build_retrieval_query(message: str, chat_history: list) -> str:
    """Augment the retrieval query with recent history so coreferences resolve correctly.

    E.g. 'What are their locations?' becomes searchable when the previous exchange
    about 'archaeological sites' is prepended.
    """
    if not chat_history:
        return message
    # Include the last human+assistant exchange (up to 2 messages)
    recent = chat_history[-2:]
    history_text = "\n".join(
        f"{m['role'].capitalize()}: {m['content']}" for m in recent
    )
    return f"{history_text}\nUser: {message}"

def init_vectorstore():
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    # allow_dangerous_deserialization=True: index is self-generated by ingest.py, not untrusted.
    db = FAISS.load_local(DB_FAISS_PATH, embeddings, allow_dangerous_deserialization=True)
    return db

@cl.on_chat_start
async def start():
    retriever = init_vectorstore().as_retriever(search_kwargs={"k": 3})
    cl.user_session.set("retriever", retriever)
    cl.user_session.set("chat_history", [])
    await cl.Message(content="Hi! Ask me anything about Indian history and culture.").send()

@cl.on_message
async def main(message: cl.Message):
    retriever = cl.user_session.get("retriever")
    chat_history: list = cl.user_session.get("chat_history")

    # Use history-augmented query so follow-up/coreference queries retrieve the right docs
    retrieval_query = build_retrieval_query(message.content, chat_history)
    docs = retriever.get_relevant_documents(retrieval_query)
    context = "\n\n".join(doc.page_content for doc in docs)

    # Build conversational message list: system (with context) + history + current turn
    messages = (
        [{"role": "system", "content": f"{SYSTEM_PROMPT}\n\nContext:\n{context}"}]
        + chat_history
        + [{"role": "user", "content": message.content}]
    )

    response = ollama.chat(model="llama2", messages=messages)
    answer = response["message"]["content"]

    # Persist the new exchange so subsequent turns can reference it
    chat_history.append({"role": "user", "content": message.content})
    chat_history.append({"role": "assistant", "content": answer})
    cl.user_session.set("chat_history", chat_history)

    if docs:
        sources = "\n".join(
            f" {doc.metadata.get('source', 'Unknown')} (pg {doc.metadata.get('page', '?')})"
            for doc in docs
        )
        answer += f"\n\nSources:\n{sources}"

    await cl.Message(content=answer).send()
