# Usage: streamlit run streamlit_main.py --server.fileWatcherType none

import os
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)

import streamlit as st
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq
from langchain.schema import SystemMessage, HumanMessage, AIMessage
from dotenv import load_dotenv

load_dotenv()

DB_FAISS_PATH = os.path.join(os.path.dirname(__file__), "vectorstore", "db_faiss")

SYSTEM_PROMPT = (
    "You are a helpful assistant knowledgeable about Indian history and culture. "
    "Use the provided context to answer questions. If the answer is not in the context, say you don't know. "
    "Be concise and helpful. Use the conversation history to resolve pronouns and follow-up references."
)

st.set_page_config(page_title="Ask Bharat", page_icon="🇮🇳")
st.title("Ask Bharat 🇮🇳")
st.markdown("Ask anything about Indian history and culture. Powered by Groq & LLaMA3.")


@st.cache_resource
def load_vectorstore():
    if not os.path.exists(DB_FAISS_PATH):
        return None
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    # allow_dangerous_deserialization=True: index is self-generated by ingest.py, not untrusted.
    return FAISS.load_local(DB_FAISS_PATH, embeddings, allow_dangerous_deserialization=True)


@st.cache_resource
def load_llm():
    groq_api_key = os.getenv("GROQ_API_KEY")
    if not groq_api_key:
        return None
    return ChatGroq(api_key=groq_api_key, model_name="llama3-70b-8192")


def build_retrieval_query(user_message: str, history: list) -> str:
    """Prepend the last exchange to the query so coreferences resolve during FAISS search.

    E.g. 'What are their locations?' becomes searchable when the previous exchange
    about 'archaeological sites' is included.
    """
    if not history:
        return user_message
    recent = history[-2:]  # last human + assistant turn
    history_text = "\n".join(
        f"{'User' if m['role'] == 'user' else 'Assistant'}: {m['content']}"
        for m in recent
    )
    return f"{history_text}\nUser: {user_message}"


# ── Startup checks ────────────────────────────────────────────────────────────

store = load_vectorstore()
if store is None:
    st.error("Vectorstore not found. Please run `python ingest.py` first.")
    st.stop()

llm = load_llm()
if llm is None:
    st.error("GROQ_API_KEY environment variable is not set. Please export it before running.")
    st.stop()

retriever = store.as_retriever(search_kwargs={"k": 3})

# ── Session state ─────────────────────────────────────────────────────────────

if "messages" not in st.session_state:
    st.session_state.messages = []  # list of {"role": "user"|"assistant", "content": str}

# ── Render existing conversation ──────────────────────────────────────────────

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# ── Handle new user input ─────────────────────────────────────────────────────

if prompt := st.chat_input("Ask a question about Indian history..."):
    # Show user message immediately
    with st.chat_message("user"):
        st.markdown(prompt)

    # Retrieve relevant docs using history-augmented query
    retrieval_query = build_retrieval_query(prompt, st.session_state.messages)
    docs = retriever.get_relevant_documents(retrieval_query)
    context = "\n\n".join(doc.page_content for doc in docs)

    # Build LangChain message list: system (with context) + full history + current turn
    lc_messages = [SystemMessage(content=f"{SYSTEM_PROMPT}\n\nContext:\n{context}")]
    for msg in st.session_state.messages:
        if msg["role"] == "user":
            lc_messages.append(HumanMessage(content=msg["content"]))
        else:
            lc_messages.append(AIMessage(content=msg["content"]))
    lc_messages.append(HumanMessage(content=prompt))

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            response = llm.invoke(lc_messages)
            answer = response.content

        st.markdown(answer)

        if docs:
            with st.expander("Sources"):
                for doc in docs:
                    src = doc.metadata.get("source", "Unknown")
                    pg = doc.metadata.get("page", "?")
                    st.markdown(f"**{src}** — page {pg}")
                    st.text(doc.page_content[:400] + ("..." if len(doc.page_content) > 400 else ""))
                    st.markdown("---")

    # Persist exchange in session state
    st.session_state.messages.append({"role": "user", "content": prompt})
    st.session_state.messages.append({"role": "assistant", "content": answer})
